apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ceph-backup.fullname" . }}
  labels:
    {{- include "ceph-backup.scheduler.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 6
  successfulJobsHistoryLimit: 24
  startingDeadlineSeconds: 1800
  jobTemplate:
    metadata:
      labels:
        {{- include "ceph-backup.scheduler.labels" . | nindent 8 }}
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "ceph-backup.scheduler.labels" . | nindent 12 }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "ceph-backup.fullname" . }}
          restartPolicy: Never
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: CEPH_MONITORS
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.cephSecretName | quote }}
                      key: monitors
                - name: CEPH_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.cephSecretName | quote }}
                      key: user
                - name: CEPH_ARGS
                  value: "--conf /var/run/secrets/ceph/rbd.conf --keyring /var/run/secrets/ceph/rbd.conf --user $(CEPH_USER)"
                - name: CEPH_SECRET_NAME
                  value: {{ .Values.cephKeySecretName | quote }}
                - name: RESTIC_SECRET_NAME
                  value: {{ .Values.resticSecretName | quote }}
              volumeMounts:
                - name: ceph
                  mountPath: /var/run/secrets/ceph
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: ceph
              secret:
                secretName: {{ .Values.cephSecretName }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
