{{ if .Values.metrics.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ceph-backup.fullname" . }}-metrics
  labels:
    {{- include "ceph-backup.metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.metrics.replicaCount }}
  selector:
    matchLabels:
      {{- include "ceph-backup.metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ceph-backup.metrics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ceph-backup.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-metrics
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ceph-backup-metrics]
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.jaeger.enabled }}
            - name: OTEL_TRACES_EXPORTER
              value: "otlp_proto_grpc"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://{{ include "ceph-backup.fullname" . }}-jaeger:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=ceph-backup-metrics"
            {{- end }}
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http-metrics
            failureThreshold: 2
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity .Values.metrics.enableAntiAffinity }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.metrics.enableAntiAffinity }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "ceph-backup.name" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
                  - key: app.kubernetes.io/component
                    operator: In
                    values:
                      - metrics
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
