---
apiVersion: v1
kind: Namespace
metadata:
  name: ceph-backup
---
apiVersion: v1
kind: Secret
metadata:
  name: restic
  namespace: ceph-backup
type: Opaque
stringData:
  url: 'rest:http://k8s-ceph:test@restic-server.restic.svc.cluster.local:8000/k8s-ceph'
  password: 'test'
