---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
---
apiVersion: v1
kind: Namespace
metadata:
  name: test2
  annotations:
    cephbackup.hpc.nyu.edu/backup: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1a
  namespace: test1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2a
  namespace: test2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2b
  namespace: test2
  annotations:
    cephbackup.hpc.nyu.edu/backup: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test2c
  namespace: test2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-3
---
apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-data
  namespace: test1
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: busybox
          args:
            - sh
            - -c
            - |
              dd if=/dev/urandom bs=1M count=5 of=/test1a/test1a.dat
          volumeMounts:
            - mountPath: /test1a
              name: test1a
      volumes:
        - name: test1a
          persistentVolumeClaim:
            claimName: test1a
---
apiVersion: batch/v1
kind: Job
metadata:
  name: initialize-data
  namespace: test2
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: busybox
          args:
            - sh
            - -c
            - |
              dd if=/dev/urandom bs=1M count=5 of=/test2a/test2a.dat
              dd if=/dev/urandom bs=1M count=5 of=/test2b/test2b.dat
              dd if=/dev/urandom bs=1M count=5 of=/test2c/test2c.dat
          volumeMounts:
            - mountPath: /test2a
              name: test2a
            - mountPath: /test2b
              name: test2b
            - mountPath: /test2c
              name: test2c
      volumes:
        - name: test2a
          persistentVolumeClaim:
            claimName: test2a
        - name: test2b
          persistentVolumeClaim:
            claimName: test2b
        - name: test2c
          persistentVolumeClaim:
            claimName: test2c
