---
apiVersion: v1
kind: Namespace
metadata:
  name:
    restic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-backups
  namespace: restic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-passwords
  namespace: restic
type: Opaque
stringData:
  # k8s-ceph:test
  htpasswd: 'k8s-ceph:$2y$05$3MBhxhG/.aCBn13sB.kGn.CgzLEGUQiznvzRcqHly.PMsARgo3g/W'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restic-server
  namespace: restic
spec:
  selector:
    matchLabels:
      app: restic-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restic-server
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
        - name: server
          #image: restic/rest-server:0.11.0
          image: quay.io/remram44/restic-server:v0.11.0-28-g2dd87ce
          env:
            - name: DATA_DIRECTORY
              value: "/data"
            - name: PASSWORD_FILE
              value: "/passwords/htpasswd"
            - name: OPTIONS
              value: "--append-only --private-repos"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /data
            - name: passwords
              mountPath: /passwords
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: restic-backups
        - name: passwords
          secret:
            secretName: restic-passwords
---
apiVersion: v1
kind: Service
metadata:
  name: restic-server
  namespace: restic
spec:
  selector:
    app: restic-server
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 8000
      targetPort: 8000
